### ISSUE TITLE
グローバル変数

### ISSUE THREAD

**Issue by hutaband** [c0a21090/ProjExD#6]
https://github.com/c0a21090/ProjExD/blob/9061bae08b3002b58a0d3709d5dbcc65de1bae0e/ex01/alphabet.py#L16
差分を求めて欠損数を出したりfor文をつかって10個取り出していたが、グローバル変数を定義して値を入れるだけでよい。

**Comment by c0a21090** [comment]
問題文を見落としていました笑　そっちの方が楽だったと思いました。
